package com.mecanica.oficina.estoque;

public class EstoqueDePecas {
    public String[] pecasAtualizadas(){
      String[] pecas =  {"Vidro para-brisa Gol",
              "Vidro para-brisa Palio",
              "Vidro para-brisa Corolla",
              "Vidro para-brisa Celta",
              "Vidro para-brisa Civic",
              "Lanterna traseira Gol",
              "Lanterna traseira Palio",
              "Lanterna traseira Fiesta",
              "Lanterna traseira Siena",
              "Lanterna traseira Voyage",
              "Parachoque dianteiro Gol",
              "Parachoque dianteiro Uno",
              "Parachoque dianteiro Fox",
              "Parachoque dianteiro HB20",
              "Parachoque dianteiro Onix",
              "Parachoque traseiro Palio",
              "Parachoque traseiro Sandero",
              "Parachoque traseiro Gol",
              "Farol dianteiro Gol",
              "Farol dianteiro Corolla",
              "Farol dianteiro Civic",
              "Farol dianteiro Uno",
              "Amortecedor dianteiro Gol",
              "Amortecedor dianteiro Palio",
              "Amortecedor dianteiro Celta",
              "Amortecedor dianteiro Onix",
              "Amortecedor dianteiro HB20",
              "Amortecedor traseiro Gol",
              "Amortecedor traseiro Fox",
              "Amortecedor traseiro Fiesta",
              "Pastilha de freio Gol",
              "Pastilha de freio Palio",
              "Pastilha de freio Civic",
              "Pastilha de freio Corolla",
              "Disco de freio Gol",
              "Disco de freio Onix",
              "Disco de freio HB20",
              "Coxim do motor Gol",
              "Coxim do motor Palio",
              "Coxim do motor Fiesta",
              "Filtro de ar Uno",
              "Filtro de ar Celta",
              "Filtro de ar Sandero",
              "Filtro de combustível Gol",
              "Filtro de combustível Classic",
              "Filtro de combustível Siena",
              "Filtro de óleo Palio",
              "Filtro de óleo Onix",
              "Bateria 60Ah Gol",
              "Bateria 60Ah Palio",
              "Bateria 60Ah Fox",
              "Bobina de ignição Gol",
              "Bobina de ignição Celta",
              "Bobina de ignição HB20",
              "Velas de ignição Uno",
              "Velas de ignição Gol",
              "Velas de ignição Civic",
              "Sensor de oxigênio Corolla",
              "Sensor de oxigênio Gol",
              "Sensor de rotação Palio",
              "Sensor de rotação Sandero",
              "Eixo homocinético Gol",
              "Eixo homocinético Palio",
              "Braço de suspensão Uno",
              "Braço de suspensão Celta",
              "Terminal de direção Gol",
              "Terminal de direção Fox",
              "Rolamento de roda Gol",
              "Rolamento de roda Onix",
              "Rolamento de roda Corolla",
              "Junta homocinética Uno",
              "Junta homocinética Siena",
              "Par de palhetas Gol",
              "Par de palhetas HB20",
              "Par de palhetas Fiesta",
              "Interruptor de luz de freio Gol",
              "Interruptor de luz de freio Fox",
              "Porta-malas Palio",
              "Porta-malas Gol",
              "Porta-malas Celta",
              "Vidro lateral Gol",
              "Vidro lateral Civic",
              "Vidro lateral Corolla",
              "Maçaneta externa Gol",
              "Maçaneta externa Palio",
              "Maçaneta externa Classic",
              "Cinto de segurança Gol",
              "Cinto de segurança Fiesta",
              "Cinto de segurança Celta",
              "Motor do limpador Gol",
              "Motor do limpador Palio",
              "Motor do limpador Fox",
              "Radiador Gol",
              "Radiador HB20",
              "Radiador Corolla",
              "Mangueira do radiador Palio",
              "Mangueira do radiador Gol",
              "Tanque de combustível Uno",
              "Tanque de combustível Gol",
              "Painel de instrumentos Palio",
              "Painel de instrumentos Gol",
              "Painel de instrumentos Fiesta"
      };
        return pecas;
    }
    }
